### PR TITLE
Add composer support

### PR DESCRIPTION
**Pull request by victorlopezg**
Just a basic composer.json file.

### CODE REVIEW

**Comment by rmccue** [comment]
Thanks!

**Comment by rmccue** [comment]
Just tried to add to Packagist and got the following:

> The package name WP-API/Basic-Auth is invalid, it should not contain uppercase characters. We suggest using wp-api/basic-auth instead.

Will fix up.

**Comment by rmccue** [comment]
Now available: https://packagist.org/packages/wp-api/basic-auth

Thanks again!

**Comment by victorlopezg** [comment]
Cool. :)

**Pull request merged**
